In [257]:
import numpy as np
import pandas as pd

In [258]:
df = pd.read_csv('./dummy.csv')
display(df.head())

Age   Fare  Survived
0   22   7.25         0
1   38  71.28         1
2   26   7.92         1
3   35  53.10         1
4   28   8.05         0

In [259]:
x_train = df[["Age","Fare"]].values
y_train = df["Survived"].values
# 30 Age, 10 Fare
x_test = np.array([38,71.28])
# tinta ximeki lol
k = 3

In [260]:
# Format
# Age, Fare
display(x_train)
# Survived column
display(y_train)
# 8 Rows
display(x_train.shape[0])

array([[22.  ,  7.25],
       [38.  , 71.28],
       [26.  ,  7.92],
       [35.  , 53.1 ],
       [28.  ,  8.05],
       [ 2.  , 21.07],
       [27.  , 11.13],
       [14.  , 30.07]])

array([0, 1, 1, 1, 0, 1, 0, 1])

8

In [261]:
# Random test gareko check garna (no need of this block)
from math import sqrt
display(x_train[0])
x, y = x_test-x_train[0] 
x_s, y_s = x**2, y**2
x_y_sum = x_s + y_s
d = sqrt(x_y_sum)
display(np.float64(d))

array([22.  ,  7.25])

np.float64(65.99879468596377)

In [262]:
# test_data ra existing training data ko euclidean distance
def euclidean_distance(training_input_data, test_input_data):
    if training_input_data.shape != test_input_data.shape:
        raise ValueError("Dimension of training and test input data must be same")
    diff = test_input_data - training_input_data
    sum_ = np.sum(diff**2)
    distance = np.sqrt(sum_)
    return distance

In [263]:
# Check gareko test code
for i in range(x_train.shape[0]):
    print(i)

0
1
2
3
4
5
6
7


In [264]:
# Harek ko individual distance , 8 wata distance point janxa
def compute_distance(x_train, x_test):
    distances = []
    for i in range(x_train.shape[0]):
        distance_individual = euclidean_distance(x_train[i], x_test)
        distances.append((distance_individual, i))
    return distances

In [265]:
g_distances = compute_distance(x_train, x_test)
try:
    assert len(g_distances) == x_train.shape[0]
    print(f"Distance computed, {x_train.shape[0]} wata distance computed")
except AssertionError as e:
    print("Assertion error, shape mismatch")

Distance computed, 8 wata distance computed


In [266]:

sorted_distances = sorted(g_distances)
top_3 = sorted_distances[0:k]
display(top_3)

display(df.loc[0,'Survived'])

def survivor_status(index):
    survived_array = []
    for i in index:
        survived_array.append(df.loc[i,'Survived'])
    return survived_array


[(np.float64(0.0), 1),
 (np.float64(18.425862259335382), 3),
 (np.float64(47.68924511878963), 7)]

np.int64(0)

In [267]:
g_indices = []
for distance, index in top_3:
    g_indices.append(index)

print(f"Indexes: {g_indices}")

Indexes: [1, 3, 7]


In [268]:
g_survivor_status = survivor_status(g_indices)
print(g_survivor_status)

[np.int64(1), np.int64(1), np.int64(1)]


In [269]:
def survived_unsurvided_count(survive_status):
    return survive_status.count(1), survive_status.count(0)

In [270]:
g_survived_count, g_death_count = survived_unsurvided_count(g_survivor_status)
print(f"Survivor count: {g_survived_count}")
print(f"Death count: {g_death_count}")

Survivor count: 3
Death count: 0


In [271]:
survived: bool = g_survived_count > g_death_count
print("Prediction, The passenger survived", survived)

Prediction, The passenger survived True
